version: "3.3"

services:

  rabbit:
    image: rabbitmq:3.7.3-management
    hostname: rabbit
    ports:
      - "5672:5672"

  consumer:
    build: ./consumer
    hostname: consumer
    links:
      - rabbit
    depends_on:
      - database
    tty: true

  producer:
    build: ./producer
    hostname: producer
    links:
      - rabbit
    tty: true

  database:
    image: postgres
    restart: always




